# Generated by Django 4.0.4 on 2022-10-19 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0, verbose_name='Quantidade de views')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_posts.publicacao')),
            ],
        ),
    ]
