# Generated by Django 4.0.4 on 2022-10-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_contadorview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Biografia do Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Imagem de perfil do Usuario'),
        ),
    ]
