# Generated by Django 4.0.4 on 2022-10-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0003_usuario_biografia_usuario_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Imagem de perfil do Usuario'),
        ),
    ]
