# Generated by Django 4.0.4 on 2022-10-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_publicacao_data_publicacao_publicacao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='UID',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código UID da publicação'),
        ),
    ]
